package model;

public enum MenuType {
    ACCOUNT_MENU,
    CREATE_ACCOUNT,
    CUSTOM_CARD_MENU,
    LOGIN,
    MAIN_MENU,
    GRAVE_YARD,
    SHOP,
    PLAYER_COLLECTION,
    PLAYING_TYPE_MENU,
    SINGLE_PLAYER_MENU,
    BATTLE,
}
